import express from "express";
import pg from "pg";
import helmet from "helmet";
import cors from "cors";
import crypto from "crypto";
const {Pool}=pg;
const app=express();
app.use(helmet({crossOriginResourcePolicy:false}));
app.use(cors({origin:["https://hfltech.in","https://www.hfltech.in"],methods:["GET","POST","PATCH"],allowedHeaders:["Content-Type","Authorization"]}));
app.use(express.json({limit:"32kb"}));
const pool=process.env.DATABASE_URL?new Pool({connectionString:process.env.DATABASE_URL,ssl:{rejectUnauthorized:false}}):null;
const ADMIN_TOKEN=process.env.ADMIN_TOKEN||"";
const PORT=process.env.PORT||10000;
const areas=["Community","Education","Technology","Cybersecurity","Content & Media","Event & Operations","Research","Student Volunteer"];
const statuses=["New","Reviewing","Shortlisted","Accepted","Rejected"];
function hashPassword(password,salt){return crypto.scryptSync(password,salt,64).toString("hex")}
function token(){return crypto.randomBytes(32).toString("hex")}
function tokenHash(t){return crypto.createHash("sha256").update(t).digest("hex")}
async function init(){if(!pool)return;await pool.query(`CREATE TABLE IF NOT EXISTS volunteer_applications(id UUID PRIMARY KEY,full_name TEXT NOT NULL,email TEXT NOT NULL,phone TEXT,location TEXT NOT NULL,age_group TEXT NOT NULL,background TEXT NOT NULL,volunteer_area TEXT NOT NULL,skills TEXT,education TEXT,experience TEXT,availability TEXT,motivation TEXT NOT NULL,portfolio TEXT,additional_info TEXT,status TEXT NOT NULL DEFAULT 'New',created_at TIMESTAMPTZ NOT NULL DEFAULT NOW())`);await pool.query(`CREATE TABLE IF NOT EXISTS hfl_users(id UUID PRIMARY KEY,email TEXT UNIQUE NOT NULL,full_name TEXT NOT NULL,password_hash TEXT NOT NULL,password_salt TEXT NOT NULL,created_at TIMESTAMPTZ NOT NULL DEFAULT NOW())`);await pool.query(`CREATE TABLE IF NOT EXISTS hfl_sessions(token_hash TEXT PRIMARY KEY,user_id UUID NOT NULL REFERENCES hfl_users(id) ON DELETE CASCADE,expires_at TIMESTAMPTZ NOT NULL)`)}
function admin(req,res,next){if(!ADMIN_TOKEN||req.headers.authorization!==`Bearer ${ADMIN_TOKEN}`)return res.status(401).json({error:"Unauthorized"});next()}
async function authUser(req,res,next){try{const raw=(req.headers.authorization||"").replace(/^Bearer /,"");if(!raw)return res.status(401).json({error:"Authentication required."});const r=await pool.query(`SELECT u.id,u.email,u.full_name FROM hfl_sessions s JOIN hfl_users u ON u.id=s.user_id WHERE s.token_hash=$1 AND s.expires_at>NOW()`,[tokenHash(raw)]);if(!r.rowCount)return res.status(401).json({error:"Session expired. Please sign in again."});req.user=r.rows[0];req.sessionToken=raw;next()}catch(e){res.status(500).json({error:"Authentication service unavailable."})}}
app.get("/health",(req,res)=>res.json({ok:true,database:!!pool}));
app.post("/api/auth/signup",async(req,res)=>{try{if(!pool)return res.status(503).json({error:"Account service database is not configured."});const b=req.body||{};const name=String(b.name||"").trim(),email=String(b.email||"").trim().toLowerCase(),password=String(b.password||"");if(name.length<2)return res.status(400).json({error:"Please enter your full name."});if(!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email))return res.status(400).json({error:"Please provide a valid email address."});if(password.length<8)return res.status(400).json({error:"Password must be at least 8 characters."});const exists=await pool.query("SELECT 1 FROM hfl_users WHERE email=$1",[email]);if(exists.rowCount)return res.status(409).json({error:"An account already exists for this email."});const id=crypto.randomUUID(),salt=crypto.randomBytes(16).toString("hex");await pool.query("INSERT INTO hfl_users(id,email,full_name,password_hash,password_salt) VALUES($1,$2,$3,$4,$5)",[id,email,name,hashPassword(password,salt),salt]);const raw=token();await pool.query("INSERT INTO hfl_sessions(token_hash,user_id,expires_at) VALUES($1,$2,NOW()+INTERVAL '30 days')",[tokenHash(raw),id]);res.status(201).json({ok:true,token:raw,redirect:"account.html"})}catch(e){console.error(e);res.status(500).json({error:"Could not create the account."})}});
app.post("/api/auth/login",async(req,res)=>{try{if(!pool)return res.status(503).json({error:"Account service database is not configured."});const email=String(req.body?.email||"").trim().toLowerCase(),password=String(req.body?.password||"");const r=await pool.query("SELECT * FROM hfl_users WHERE email=$1",[email]);if(!r.rowCount)return res.status(401).json({error:"Invalid email or password."});const u=r.rows[0];if(hashPassword(password,u.password_salt)!==u.password_hash)return res.status(401).json({error:"Invalid email or password."});const raw=token();await pool.query("INSERT INTO hfl_sessions(token_hash,user_id,expires_at) VALUES($1,$2,NOW()+INTERVAL '30 days')",[tokenHash(raw),u.id]);res.json({ok:true,token:raw,redirect:"account.html"})}catch(e){console.error(e);res.status(500).json({error:"Could not sign you in."})}});
app.get("/api/auth/me",authUser,async(req,res)=>res.json({ok:true,user:req.user}));
app.post("/api/auth/logout",authUser,async(req,res)=>{await pool.query("DELETE FROM hfl_sessions WHERE token_hash=$1",[tokenHash(req.sessionToken)]);res.json({ok:true})});
app.post("/api/auth/reset",async(req,res)=>{res.json({ok:true,message:"If an account exists for that email, recovery instructions can be sent once email delivery is configured."})});
app.post("/api/volunteers",async(req,res)=>{try{if(!pool)return res.status(503).json({error:"Application service is not connected to its database yet."});const b=req.body||{};const required=["fullName","email","location","ageGroup","background","volunteerArea","motivation"];if(required.some(k=>typeof b[k]!=="string"||!b[k].trim()))return res.status(400).json({error:"Please complete all required fields."});if(!areas.includes(b.volunteerArea))return res.status(400).json({error:"Invalid volunteer area."});if(!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(b.email))return res.status(400).json({error:"Please provide a valid email address."});const id=crypto.randomUUID();await pool.query(`INSERT INTO volunteer_applications(id,full_name,email,phone,location,age_group,background,volunteer_area,skills,education,experience,availability,motivation,portfolio,additional_info) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14,$15)`,[id,b.fullName.trim(),b.email.trim(),b.phone||"",b.location.trim(),b.ageGroup,b.background,b.volunteerArea,b.skills||"",b.education||"",b.experience||"",b.availability||"",b.motivation.trim(),b.portfolio||"",b.additionalInfo||""]);res.status(201).json({ok:true,id});}catch(e){console.error(e);res.status(500).json({error:"Application could not be submitted."})}});
app.get("/api/admin/volunteers",admin,async(req,res)=>{try{const q=req.query.status;const r=q&&statuses.includes(q)?await pool.query("SELECT * FROM volunteer_applications WHERE status=$1 ORDER BY created_at DESC",[q]):await pool.query("SELECT * FROM volunteer_applications ORDER BY created_at DESC");res.json(r.rows)}catch(e){res.status(500).json({error:"Could not load applications."})}});
app.patch("/api/admin/volunteers/:id",admin,async(req,res)=>{try{if(!statuses.includes(req.body.status))return res.status(400).json({error:"Invalid status."});const r=await pool.query("UPDATE volunteer_applications SET status=$1 WHERE id=$2 RETURNING *",[req.body.status,req.params.id]);if(!r.rowCount)return res.status(404).json({error:"Application not found."});res.json(r.rows[0])}catch(e){res.status(500).json({error:"Could not update application."})}});
init().then(()=>app.listen(PORT,()=>console.log(`HFL API listening on ${PORT}`))).catch(e=>{console.error(e);process.exit(1)});